# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package.json .

# Install Angular CLI globally (optional)
RUN npm install -g @angular/cli

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
# COPY src  /app


# Build the Angular app
RUN ng build

# Expose port 80 for the Angular app (adjust as needed)
EXPOSE 4200

# Define the command to start the Angular app
#CMD ["ng", "serve", "--proxy-config", "proxy.conf.json", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
CMD ["ng", "serve",  "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
